### ISSUE TITLE
🐛A bug in Caséologue or in me? 🤷🏽‍♀️

### ISSUE THREAD

**Issue by matuskalas** [edamontology/caseologue#21]
Am I again missing something and did something severe? 😱
Or is this a 🐞?
![image](https://github.com/edamontology/caseologue/assets/992660/253dbab0-16c6-48be-92e3-067822411572)
Thanks for checking @hmenager or @albangaignard 🙏🏽🙇🏽‍♂️

**Comment by hmenager** [comment]
None of these @matuskalas:
- you didn't break anything
- caseologue isn't broken

I think it's a matter of dependency versions, as mentionned in https://stackoverflow.com/questions/78634235/numpy-dtype-size-changed-may-indicate-binary-incompatibility-expected-96-from.

I'll go with the recommended fix, pin reqs for Numpy to `numpy==1.26.4`.

**Comment by hmenager** [comment]
Should be fixed by d38b999.
